// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v7.34.1
// source: signals.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	SignalStreamer_SubscribeSignals_FullMethodName = "/signals.v1.SignalStreamer/SubscribeSignals"
)

// SignalStreamerClient is the client API for SignalStreamer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SignalStreamerClient interface {
	// Server streaming RPC for subscribing to signals
	SubscribeSignals(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (SignalStreamer_SubscribeSignalsClient, error)
}

type signalStreamerClient struct {
	cc grpc.ClientConnInterface
}

func NewSignalStreamerClient(cc grpc.ClientConnInterface) SignalStreamerClient {
	return &signalStreamerClient{cc}
}

func (c *signalStreamerClient) SubscribeSignals(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (SignalStreamer_SubscribeSignalsClient, error) {
	stream, err := c.cc.NewStream(ctx, &SignalStreamer_ServiceDesc.Streams[0], SignalStreamer_SubscribeSignals_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &signalStreamerSubscribeSignalsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SignalStreamer_SubscribeSignalsClient interface {
	Recv() (*ActionSignal, error)
	grpc.ClientStream
}

type signalStreamerSubscribeSignalsClient struct {
	grpc.ClientStream
}

func (x *signalStreamerSubscribeSignalsClient) Recv() (*ActionSignal, error) {
	m := new(ActionSignal)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SignalStreamerServer is the server API for SignalStreamer service.
// All implementations must embed UnimplementedSignalStreamerServer
// for forward compatibility
type SignalStreamerServer interface {
	// Server streaming RPC for subscribing to signals
	SubscribeSignals(*SubscribeRequest, SignalStreamer_SubscribeSignalsServer) error
	mustEmbedUnimplementedSignalStreamerServer()
}

// UnimplementedSignalStreamerServer must be embedded to have forward compatible implementations.
type UnimplementedSignalStreamerServer struct {
}

func (UnimplementedSignalStreamerServer) SubscribeSignals(*SubscribeRequest, SignalStreamer_SubscribeSignalsServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeSignals not implemented")
}
func (UnimplementedSignalStreamerServer) mustEmbedUnimplementedSignalStreamerServer() {}

// UnsafeSignalStreamerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SignalStreamerServer will
// result in compilation errors.
type UnsafeSignalStreamerServer interface {
	mustEmbedUnimplementedSignalStreamerServer()
}

func RegisterSignalStreamerServer(s grpc.ServiceRegistrar, srv SignalStreamerServer) {
	s.RegisterService(&SignalStreamer_ServiceDesc, srv)
}

func _SignalStreamer_SubscribeSignals_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SignalStreamerServer).SubscribeSignals(m, &signalStreamerSubscribeSignalsServer{stream})
}

type SignalStreamer_SubscribeSignalsServer interface {
	Send(*ActionSignal) error
	grpc.ServerStream
}

type signalStreamerSubscribeSignalsServer struct {
	grpc.ServerStream
}

func (x *signalStreamerSubscribeSignalsServer) Send(m *ActionSignal) error {
	return x.ServerStream.SendMsg(m)
}

// SignalStreamer_ServiceDesc is the grpc.ServiceDesc for SignalStreamer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SignalStreamer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "signals.v1.SignalStreamer",
	HandlerType: (*SignalStreamerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeSignals",
			Handler:       _SignalStreamer_SubscribeSignals_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "signals.proto",
}
