// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v7.34.1
// source: signals.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SignalLevel int32

const (
	SignalLevel_INFO     SignalLevel = 0
	SignalLevel_WARNING  SignalLevel = 1
	SignalLevel_CRITICAL SignalLevel = 2
)

// Enum value maps for SignalLevel.
var (
	SignalLevel_name = map[int32]string{
		0: "INFO",
		1: "WARNING",
		2: "CRITICAL",
	}
	SignalLevel_value = map[string]int32{
		"INFO":     0,
		"WARNING":  1,
		"CRITICAL": 2,
	}
)

func (x SignalLevel) Enum() *SignalLevel {
	p := new(SignalLevel)
	*p = x
	return p
}

func (x SignalLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SignalLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_signals_proto_enumTypes[0].Descriptor()
}

func (SignalLevel) Type() protoreflect.EnumType {
	return &file_signals_proto_enumTypes[0]
}

func (x SignalLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SignalLevel.Descriptor instead.
func (SignalLevel) EnumDescriptor() ([]byte, []int) {
	return file_signals_proto_rawDescGZIP(), []int{0}
}

// The request message containing optional filters
type SubscribeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// e.g. "FCM", "IdentityToolkit", or empty for all
	ApiFilter string `protobuf:"bytes,1,opt,name=api_filter,json=apiFilter,proto3" json:"api_filter,omitempty"`
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_signals_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_signals_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_signals_proto_rawDescGZIP(), []int{0}
}

func (x *SubscribeRequest) GetApiFilter() string {
	if x != nil {
		return x.ApiFilter
	}
	return ""
}

// The response message containing the signal
type ActionSignal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Api       string                 `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Level     SignalLevel            `protobuf:"varint,3,opt,name=level,proto3,enum=signals.v1.SignalLevel" json:"level,omitempty"`
	Message   string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ActionSignal) Reset() {
	*x = ActionSignal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_signals_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActionSignal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionSignal) ProtoMessage() {}

func (x *ActionSignal) ProtoReflect() protoreflect.Message {
	mi := &file_signals_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionSignal.ProtoReflect.Descriptor instead.
func (*ActionSignal) Descriptor() ([]byte, []int) {
	return file_signals_proto_rawDescGZIP(), []int{1}
}

func (x *ActionSignal) GetApi() string {
	if x != nil {
		return x.Api
	}
	return ""
}

func (x *ActionSignal) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ActionSignal) GetLevel() SignalLevel {
	if x != nil {
		return x.Level
	}
	return SignalLevel_INFO
}

func (x *ActionSignal) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_signals_proto protoreflect.FileDescriptor

var file_signals_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0a, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x73, 0x2e, 0x76, 0x31, 0x1a, 0x1f, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x31, 0x0a, 0x10,
	0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x70, 0x69, 0x5f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x70, 0x69, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x22,
	0xa3, 0x01, 0x0a, 0x0c, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c,
	0x12, 0x10, 0x0a, 0x03, 0x61, 0x70, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x61,
	0x70, 0x69, 0x12, 0x38, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x2d, 0x0a, 0x05,
	0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x73, 0x69,
	0x67, 0x6e, 0x61, 0x6c, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x4c,
	0x65, 0x76, 0x65, 0x6c, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x2a, 0x32, 0x0a, 0x0b, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x4c,
	0x65, 0x76, 0x65, 0x6c, 0x12, 0x08, 0x0a, 0x04, 0x49, 0x4e, 0x46, 0x4f, 0x10, 0x00, 0x12, 0x0b,
	0x0a, 0x07, 0x57, 0x41, 0x52, 0x4e, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x43,
	0x52, 0x49, 0x54, 0x49, 0x43, 0x41, 0x4c, 0x10, 0x02, 0x32, 0x60, 0x0a, 0x0e, 0x53, 0x69, 0x67,
	0x6e, 0x61, 0x6c, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x65, 0x72, 0x12, 0x4e, 0x0a, 0x10, 0x53,
	0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x73, 0x12,
	0x1c, 0x2e, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x75, 0x62,
	0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e,
	0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x22, 0x00, 0x30, 0x01, 0x42, 0x2f, 0x5a, 0x2d, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x61, 0x64, 0x64, 0x79, 0x7a,
	0x61, 0x62, 0x2f, 0x67, 0x63, 0x63, 0x2d, 0x64, 0x61, 0x74, 0x61, 0x2d, 0x70, 0x6f, 0x6c, 0x6c,
	0x65, 0x72, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_signals_proto_rawDescOnce sync.Once
	file_signals_proto_rawDescData = file_signals_proto_rawDesc
)

func file_signals_proto_rawDescGZIP() []byte {
	file_signals_proto_rawDescOnce.Do(func() {
		file_signals_proto_rawDescData = protoimpl.X.CompressGZIP(file_signals_proto_rawDescData)
	})
	return file_signals_proto_rawDescData
}

var file_signals_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_signals_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_signals_proto_goTypes = []interface{}{
	(SignalLevel)(0),              // 0: signals.v1.SignalLevel
	(*SubscribeRequest)(nil),      // 1: signals.v1.SubscribeRequest
	(*ActionSignal)(nil),          // 2: signals.v1.ActionSignal
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_signals_proto_depIdxs = []int32{
	3, // 0: signals.v1.ActionSignal.timestamp:type_name -> google.protobuf.Timestamp
	0, // 1: signals.v1.ActionSignal.level:type_name -> signals.v1.SignalLevel
	1, // 2: signals.v1.SignalStreamer.SubscribeSignals:input_type -> signals.v1.SubscribeRequest
	2, // 3: signals.v1.SignalStreamer.SubscribeSignals:output_type -> signals.v1.ActionSignal
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_signals_proto_init() }
func file_signals_proto_init() {
	if File_signals_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_signals_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubscribeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_signals_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActionSignal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_signals_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_signals_proto_goTypes,
		DependencyIndexes: file_signals_proto_depIdxs,
		EnumInfos:         file_signals_proto_enumTypes,
		MessageInfos:      file_signals_proto_msgTypes,
	}.Build()
	File_signals_proto = out.File
	file_signals_proto_rawDesc = nil
	file_signals_proto_goTypes = nil
	file_signals_proto_depIdxs = nil
}
